version: "3.7"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.conda
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file: ./.env
    image: andreburto/jupyter2
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./notebook
        target: /notebook
  postgres:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file: ./.env
    image: postgres:9.4
    networks:
      - backend
    volumes:
      - type: bind
        source: ./postgres
        target: /var/lib/postgresql/data

networks:
  backend:
