name: xeus-sqlite
channels:
  - conda-forge
  - javascript
dependencies:
  - boto3=1.14.12
  - bokeh=
  - bs4=4.9.1
  - git=2.23.0
  - ipywidgets=7.5.1
  - nodejs=0.10.*
  - notebook=6.0.3
  - numpy
  - flask
  - psycopg2=2.8.4
  - PyMySQL=0.9.2
  - python=3.7.*
  - requests=2.24.0
  - sqlite
  - xeus-sqlite
  - pip:
    - git+https://github.com/andreburto/brickulator.git@master#egg=brickulator