#!/usr/bin/env bash
# Run my Jupyter container. Build it if it doesn't exist.

IMAGE_NAME="andreburto/jupyter1"

cd $(dirname $0)

if [ ! -f $(pwd)/Dockerfile ]; then
  echo "Dockerfile missing."
  exit 1
fi

docker build . -t $IMAGE_NAME:latest

mkdir -p notebook

docker run -it --mount type=bind,source=$(pwd)/notebook,target=/notebook -p 8888:8888 $IMAGE_NAME
