#!/usr/bin/env bash
# Run my Jupyter container. Build it if it doesn't exist.

IMAGE_NAME="andreburto/jupyter1"

cd $(dirname $0)

if [ $(docker image ls $IMAGE_NAME | grep $IMAGE_NAME) == ""]; then
    if [ -f Dockerfile ]; then
        docker build . -t $IMAGE_NAME:latest
    else
        echo "Dockerfile missing."
        exit 1
    fi
fi

mkdir -p notebook

docker run -it --mount type=bind,source=$(pwd)/notebook,target=/notebook -p 8888:8888 $IMAGE_NAME
