#!/usr/bin/env bash
# Run my Jupyter container. Build it if it doesn't exist.
cd $(dirname $0)

IMAGE_NAME="andreburto/jupyter1"
ENV_FILE="$(pwd)/.env"

if [[ ! -f $ENV_FILE ]]; then
  echo "No environment file."
  exit 1
fi

if [[ ! -f $(pwd)/Dockerfile ]]; then
  echo "Dockerfile missing."
  exit 1
fi

docker build . -t $IMAGE_NAME:latest

mkdir -p notebook

docker run -it --env-file=$ENV_FILE --mount type=bind,source=$(pwd)/notebook,target=/notebook -p 8888:8888 $IMAGE_NAME
